version: '3'
services:
  server: #name of the second service
    build: BackArqui # specify the directory of the Dockerfile
    ports:
      - "8080:8080" #specify ports forewarding
    links: 
      - database
  database:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - //c/Users/Duivan/PostgresDockerData:/backup